name: Periodic health check

on:
  push:
    branches:
      - healthcheck

jobs:
  periodic_healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://whispering-headland-54961.herokuapp.com/health
          #follow-redirect: no
          #max-attempts: 3
          #retry-delay: 5s
          #retry-all: no
