name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    env:
      COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
    steps:
      - name: commit messages
        run: echo "hello $COMMIT_MESSAGES"
      - name: constains skip
        #if: ${{ contains(join('-', github.event.commits.*.message), 'skip') }}
        if: ${{ contains(github.event.commits.head_commit.message, '#skip') }}
        run: echo "true"
      - name: does not contain skip
        if: ${{ !contains(join('-', github.event.commits.*.message), 'skip') }}
        run: echo "true"
